name: mxflutter
description: JavaScript Flutter Framework,Using mxflutter lib, you can use JavaScript to develop flutter or use Dart to develop and compile to JS.
version: 0.9.0
homepage: https://github.com/mxflutter/mxflutter

environment:
  sdk: '^3.3.0'
dependencies:
  js: ^0.6.2
